### ISSUE TITLE
download pdf function not working

### ISSUE THREAD

**Issue by HailGoosifer** [LibreScore/dl-librescore#48] opened 2024-02-07 01:36 UTC
although midi and mp3 work fine

**Comment by Cobertos** [comment] 2024-02-07 07:57
As a workaround, you can download the MIDI and upload it to [WebmScore](https://webmscore-pwa.librescore.org/) (linked at the bottom of the readme) and convert it to PDF. Not sure if that will work with _every_ score, but it worked for mine.

**Comment by ChispaCulpable343** [comment] 2024-02-08 02:19
Yup, as today 07/02/24, pdf function is still not working

**Comment by DereC4** [comment] 2024-02-08 07:06
Can confirm

**Comment by m1n3nfux** [comment] 2024-02-08 11:51
Here too, at least i think it is related. I get the following Error using npx dl-librescore@latest

```⠂ Processing…/Users/user/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:4711
    return info.url;
                ^

TypeError: Cannot read properties of null (reading 'url')
    at /Users/user/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:4711:17
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:17:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by grida-nanna** [comment] 2024-02-08 16:56
Hi there.
I have the same problem. I have no programming skills but, at least in Firefox, it seems to have to do with some video and picture-in-picture function that seems to keep on reloading every time I press "download pdf"

**Comment by PeterNjeim** [comment] 2024-02-09 07:36
Duplicate of #45

**Closed by PeterNjeim** 2024-02-09 07:36 UTC
Labels: bug, duplicate
