### ISSUE TITLE
Command Line Tool not working

### ISSUE THREAD

**Issue by MaxedShroom** [LibreScore/dl-librescore#74] opened 2024-08-07 17:59 UTC
When pasting in the link it will print score not found. 
<img width="384" alt="Screenshot 2024-08-07 at 1 58 58 PM" src="https://github.com/user-attachments/assets/5bee0509-bb80-4327-b804-ef35674ed7b6">

**Comment by PeterNjeim** [comment] 2024-08-11 06:00
I can't reproduce the issue:
![image](https://github.com/user-attachments/assets/60a5198c-e06a-4ec4-ba68-6f6309264c0d)

Can you share what your node and npm versions are?
```
node --version
v20.14.0 // my version
```
```
npm --version
10.4.0 // my version
```

**Comment by gnvdude** [comment] 2024-10-02 16:31
ya I wish there were working command line switches for input of file, and selecting output file type and location

**Comment by PeterNjeim** [comment] 2024-10-02 17:01
Closing in favor of https://github.com/LibreScore/dl-librescore/issues/81

**Closed** 2024-10-02 17:01 UTC
Labels: duplicate, invalid
