### ISSUE TITLE
Browser Extension Downloads Only One Page

### ISSUE THREAD

**Issue by fonky415** [LibreScore/dl-librescore#78] opened 2024-09-04 13:36 UTC
Are scores like [this](https://musescore.com/user/39593079/scores/16198786) just not accessible because preview ends in one page? Or must I use command line to download PDF?

**Comment by blade2005** [comment] 2024-09-04 13:36
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by PeterNjeim** [comment] 2024-09-06 16:24
Duplicate of https://github.com/LibreScore/dl-librescore/issues/10

**Closed by PeterNjeim** 2024-09-06 16:24 UTC
Labels: duplicate, invalid
