### ISSUE TITLE
Browser extension can't download files

### ISSUE THREAD

**Issue by gamono23** [LibreScore/dl-librescore#45] opened 2024-01-31 16:29 UTC
I thought it was just on one score, but checking other one returns same result :( I can't really give any of useful information, and sorry about that

![image](https://github.com/LibreScore/dl-librescore/assets/108485572/040da866-1f26-4c19-9113-597b9583dd22)
![image](https://github.com/LibreScore/dl-librescore/assets/108485572/d562789c-7f64-4654-b08b-ad6880b99a9b)

**Comment by PeterNjeim** [comment] 2024-01-31 19:10
The file is downloading correctly for me, this score: https://musescore.com/user/11512151/scores/5581047, right?

Please try again and see if it works

**Comment by Cybernetic-Fox** [comment] 2024-02-01 02:51
I run the Tampermonkey with the Brave Browser on PC.

Specifically, I block with very specific settings. Not allowing anything to track me.

I do it in the order that follows:

1. Open the desires musescore site
2. Select the Brave logo icon in the right side of the search bar.
3. In advanced controls: [Block trackers & ads], [Upgrade connection to HTTPS], [Do not touch the block scripts yet], [Block Fingerprinting], [Block all cookies], and [Forget me when I close this site] on.

**After that, continue with the following as fast as possible.**

1. Turn on Tampermonkey with the loaded script (using the latest version that came out 3 weeks ago)
2. Reopen the Brave logo in the search bar and turn on [Block all scripts] until the screen turns white.
3. Once the screen is all white, turn off [Block all scripts] and select Midi.
4. The MIDI should be downloaded in a few seconds.

**Comment by PeterNjeim** [comment] 2024-02-01 03:07
Thanks for the information. Maybe one of MuseScore's backend servers was added to a tracker list? I use uBlock Origin which also blocks trackers but it works for me. I'll contact the others who reported this problem on Discord and see what their browser situation is

**Comment by Cybernetic-Fox** [comment] 2024-02-01 03:09
You're welcome. I'm so glad I was able to help! :3

**Comment by Avanatiker** [comment] 2024-02-01 03:19
For others: You can get the data on `about:support`

- **Name:** Firefox
- **OS Version:** Linux 6.7.2-arch1-1 # 1 SMP PREEMPT_DYNAMIC Fri, 26 Jan 2024 19:10:20 +0000
- **Version:** 122.0
- **Build ID:** 20240123151424
- **Distribution ID:** archlinux
- **User Agent:** Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
- **Safe Mode:** false
- **Memory Size (Bytes):** 67364679680
- **Disk Available (Bytes):** 41224183808
- **Support URL:** [https://support.mozilla.org/1/firefox/122.0/Linux/en-US/](https://support.mozilla.org/1/firefox/122.0/Linux/en-US/)
- **OS Theme:** Breeze / Adwaita
- **Number of Total Windows:** 1
- **Number of Fission Windows:** 1
- **Number of Remote Windows:** 1
- **Fission Auto Start:** true
- **Fission Decision Status:** enabledByDefault
- **Remote Auto Start:** true
- **Policies Status:** 0
- **Key Location Service Google Found:** true
- **Key Safebrowsing Google Found:** true
- **Key Mozilla Found:** true
  
 **Extensions:**

1. 7TV Nightly
2. base64 decoder
3. Bitwarden - Free Password Manager
4. ClearURLs
5. Dark Reader
6. HistoryBlock
7. I still don't care about cookies
8. Return YouTube Dislike
9. SponsorBlock for YouTube - Skip Sponsorships
10. Tampermonkey
11. TTV LOL PRO
12. uBlock Origin
13. User-Agent Switcher and Manager
14. YouTube NonStop

**Comment by PeterNjeim** [comment] 2024-02-01 04:04
Some possible culprits based on messages on Discord:

Firefox itself doesn't work

For chromium, it's hit or miss, I can't reproduce it

**Comment by PeterNjeim** [comment] 2024-02-09 07:37
Reopening to track PDF download issue after fallback used in https://github.com/LibreScore/dl-librescore/commit/fc99d7fd9b32f0eeaec79a657268f6060bdb341b patched

**Comment by PeterNjeim** [comment] 2024-02-10 06:19
Fixed in https://github.com/LibreScore/dl-librescore/commit/772e7b37a13c93244077149c3c24378ac0099d86

**Closed by PeterNjeim** 2024-02-10 06:19 UTC
Labels: bug
