### ISSUE TITLE
Can't download .MSCZ files

### ISSUE THREAD

**Issue by ChithilaW** [LibreScore/dl-librescore#69] opened 2024-06-23 18:09 UTC
I downloaded the Liberscore App and tried to covert [Pirates Of The Caribbean](https://musescore.com/user/4841481/scores/9412102). But it gave an error when I tried to download the file.

P.S. 
  This is my first time reporting an issue/bug here so please tell me if I'm doing something wrong

**Comment by PeterNjeim** [comment] 2024-06-26 23:52
Wrong repository, duplicate of https://github.com/LibreScore/dl-librescore/issues/4

**Closed by PeterNjeim** 2024-06-26 23:52 UTC
Labels: duplicate, invalid
