### ISSUE TITLE
Downloading PDF isn't working

### ISSUE THREAD

**Issue by mightbebored** [LibreScore/dl-librescore#52] opened 2024-02-14 21:37 UTC
the pdfs appear as corrupted when i use the node.js installer and i cant download at all with the tampermonkey installer or the chrome extension.

**Comment by PeterNjeim** [comment] 2024-02-17 04:05
First issue is duplicate of https://github.com/LibreScore/dl-librescore/issues/44

As for the second issue, the problem is not reproducible, and there is no chrome extension. Please share logs and other details such as the song you're trying to download, the browser you're using, any extensions, etc.

**Comment by PeterNjeim** [comment] 2024-02-21 07:57
Closing because this problem is probably a temporary failure from https://github.com/LibreScore/dl-librescore/issues/51

**Closed by PeterNjeim** 2024-02-21 07:57 UTC
Labels: help wanted
