### ISSUE TITLE
Server Error | Get Support

### ISSUE THREAD

**Issue by saleem0915** [LibreScore/dl-librescore#70] opened 2024-07-05 01:20 UTC
I'm 100% sure this has been asked probably over 100 times but I'm going to ask. I'm trying to download a transcription of the [Merry Go Round of Life from Howl's Moving Castle](https://musescore.com/user/34214067/merry-go-round-of-life), but every time and every format I try to download it in, it says Server Error and to the right, Get Support which leads me to a Discord Sever that I really don't wan to join. Any fixes? I am using the latest version (from [https://github.com/LibreScore/app-librescore/releases/latest/download/LibreScore.exe](https://github.com/LibreScore/app-librescore/releases/latest/download/LibreScore.exe)), and I am running Windows 10 version 1703 (I like this version of the OS). I have resorted to using the command line interface and that so far has worked. 

Thank you and happy 4th

Edit: Added details of MuseScore song, OS Specs and librescore app version

**Comment by PeterNjeim** [comment] 2024-07-05 02:02
Wrong repository, duplicate of https://github.com/LibreScore/dl-librescore/issues/4

**Closed by PeterNjeim** 2024-07-05 02:02 UTC
Labels: duplicate, invalid
