### ISSUE TITLE
Downloads failing (CLI)

### ISSUE THREAD

**Issue by halpz** [LibreScore/dl-librescore#57] opened 2024-03-01 09:21 UTC
here is my log:

```
% npx dl-librescore@latest
(node:76305) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
? MuseScore URL or path to file or folder:
  (starts with https://musescore.com/ or is a path) 
  https://musescore.com/user/668541/scores/2469096
! ID: 2469096
  Title: The Frog Galliard (Piano)
  Continue? Yes

? Filetype Selection pdf
? Output Directory: /Users/halpz/Downloads
⠁ Processing…node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "function Error() { [native code] }".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by Florisv1** [comment] 2024-03-01 11:00
Yes, only the browser extension, Usermonkey, script works at the moment. I read in another GitHub issue they'll try to fix the other scripts/apps.

**Comment by Florisv1** [comment] 2024-03-01 11:02
Are you trying to automate downloading pdf files? Or do you want to manually download a certain file?

**Comment by PeterNjeim** [comment] 2024-03-02 21:47
Duplicate of https://github.com/LibreScore/dl-librescore/issues/44

**Closed** 2024-03-02 21:48 UTC
Labels: bug, duplicate
