### ISSUE TITLE
Invalid URL when using CLI

### ISSUE THREAD

**Issue by jakobpack** [LibreScore/dl-librescore#68] opened 2024-05-31 07:29 UTC
### Output of `npx dl-librescore@latest`

```
? MuseScore URL or path to file or folder:
  (starts with https://musescore.com/ or is a path) 
  https://musescore.com/user/189765/scores/5463306
! ID: 5463306
  Title: Somewhere Only We Know - Keane
  Continue? Yes

? Filetype Selection pdf
? Output Directory: Downloads
⠂ Processing…node:internal/deps/undici/undici:12502
      Error.captureStackTrace(err, this);
            ^

TypeError: Failed to parse URL from undefined
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at new Request (node:internal/deps/undici/undici:4853:25)
      at fetch (node:internal/deps/undici/undici:9662:25)
      at fetch (node:internal/deps/undici/undici:12500:10)
      at value (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at /Users/jakobpack/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:4947:28
      at Generator.next (<anonymous>)
      at fulfilled (/Users/jakobpack/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:17:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ERR_INVALID_URL',
    input: 'undefined'
  }
}

Node.js v20.14.0
```

Selecting `pdf`or `mp3` in this case throws this error. The `midi` option works fine.

**Comment by PeterNjeim** [comment] 2024-06-05 16:02
MIDI fails as well now, will look into it

**Comment by PeterNjeim** [comment] 2024-06-05 16:31
Seems to either be a MuseScore issue or a LibreScore issue, can't tell for sure

**Comment by PeterNjeim** [comment] 2024-06-05 16:42
Seems to be related to: https://github.com/LibreScore/dl-librescore/pull/62#issuecomment-2130811330

**Comment by PeterNjeim** [comment] 2024-06-05 17:36
Fixed in: https://github.com/LibreScore/dl-librescore/commit/aa4fc038e09918d6442e84d3eed5181347c12b41

**Closed by PeterNjeim** 2024-06-05 17:36 UTC
Labels: bug, musescore issue

**Comment by lumtvn** [comment] 2024-06-26 23:10
i had a similar issue. im running macOS 13.6.7 and node v18.13.0

```
node ./dist/cli.js
? MuseScore URL or path to file or folder:
  (starts with https://musescore.com/ or is a path) 
  https://musescore.com/user/28059929/scores/5646735
! ID: 5646735
  Title: Super Mario World - Castle Theme
  Continue? Yes

? Filetype Selection pdf
? Output Directory: /Users/lucianomantovani/repos/dl-librescore
⠁ Processing…node:internal/deps/undici/undici:14062
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from undefined
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:400:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:6914:25)
      at fetch2 (node:internal/deps/undici/undici:13228:25)
      at Object.fetch (node:internal/deps/undici/undici:14060:18)
      at fetch (node:internal/process/pre_execution:237:25)
      at /Users/lucianomantovani/repos/dl-librescore/dist/cli.js:4947:28
      at Generator.next (<anonymous>)
      at fulfilled (/Users/lucianomantovani/repos/dl-librescore/dist/cli.js:17:58) {
    input: 'undefined',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.13.0
```

i tried debugging on line 4941 of cli.js where it fetches the text from the url and tries to match, but the 'static' link doesn't seem to be inside the text. I just came across this repo yesterday so sorry if i'm missing anything obvious.

Result from the fetch line:
[scoreUrl text.txt](https://github.com/user-attachments/files/15997376/scoreUrl.text.txt)

**Comment by PeterNjeim** [comment] 2024-06-26 23:58
@lumtvn I can't reproduce, however, it appears you're being rate limited by MuseScore. Can you confirm if you can access the link to the song you want to download in a browser?

**Comment by akaita** [comment] 2024-07-05 21:02
I was having the same issue with node 18.15.0
I updated to node v22.4.0 (npm v10.8.1) and it just worked. I could download mp3&midi&pdf
