### ISSUE TITLE
2024.03.10.can't download

### ISSUE THREAD

**Issue by ilyapricot** [LibreScore/dl-librescore#59] opened 2024-03-10 04:07 UTC
2024.03.10.can't download, ID:c67

**Comment by a1004849447** [comment] 2024-03-10 04:15
I can't download it either

**Comment by stsm85** [comment] 2024-03-13 01:30
me too，我也下不了了

**Comment by PeterNjeim** [comment] 2024-03-14 16:11
Wrong repository, also duplicate of https://github.com/LibreScore/dl-librescore/issues/4

**Closed by PeterNjeim** 2024-03-14 16:11 UTC
Labels: duplicate, invalid
