### ISSUE TITLE
Command Line Tool not Working - Issue in Processing step

### ISSUE THREAD

**Issue by mlq1819** [LibreScore/dl-librescore#75] opened 2024-08-18 21:49 UTC
I am running into an issue with the processing step. I am successfully able to retrieve data on the song from the url, but am running into difficulties actually downloading it. 

When attempting to perform the processing step, a TypeError occurs:

![image](https://github.com/user-attachments/assets/5e7f7919-855d-46b8-9737-5735c29a0465)

This happens for any type of conversion: I also attempted midi and mp3.

![image](https://github.com/user-attachments/assets/e81e28a2-2900-4f5f-924e-1f81899db28f)

**Comment by PeterNjeim** [comment] 2024-08-19 19:12
Duplicate of #68 

See this comment: https://github.com/LibreScore/dl-librescore/issues/68#issuecomment-2211409818

**Closed by PeterNjeim** 2024-08-19 19:12 UTC
Labels: bug, duplicate
