### ISSUE TITLE
Download buttons won't show until entering the inspect element tool

### ISSUE THREAD

**Issue by Mikemin291** [LibreScore/dl-librescore#76] opened 2024-08-28 23:44 UTC

**Comment by PeterNjeim** [comment] 2024-08-30 20:16
Can't reproduce. Share more details about your browser, extension version, score being viewed, etc.

**Comment by PeterNjeim** [comment] 2024-12-06 08:55
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)

**Closed by PeterNjeim** 2024-12-06 08:55 UTC
Labels: help wanted
