### ISSUE TITLE
i think its broken? 

### ISSUE THREAD

**Issue by stwongy** [LibreScore/dl-librescore#58] opened 2024-03-04 05:24 UTC
I am sorry if it isn't but it was just working yesterday but, not anymore

**Comment by ScriptKiddieOnAJourney** [comment] 2024-03-06 22:32
> Yeah, it's just... broken. It doesn't download a file

In fact, it performs all the actions it should, but then it just doesn't download it.

**Comment by qqwui** [comment] 2024-03-08 22:10
Download MIDI fails with this on Firefox Version 123.0 (64-bit):
```
Error: token timeout
    timer https://musescore.com/pimplup/an-ending:26753
    setTimeout handler*getApiAuth/</< https://musescore.com/pimplup/an-ending:26752
    getApiAuth https://musescore.com/pimplup/an-ending:26751
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getApiAuth https://musescore.com/pimplup/an-ending:26697
    getFileUrl https://musescore.com/pimplup/an-ending:26779
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getFileUrl https://musescore.com/pimplup/an-ending:26776
    action https://musescore.com/pimplup/an-ending:31365
    normalizeUrlInput https://musescore.com/pimplup/an-ending:31193
    download https://musescore.com/pimplup/an-ending:31199
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    download https://musescore.com/pimplup/an-ending:31198
    process https://musescore.com/pimplup/an-ending:31214
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    process https://musescore.com/pimplup/an-ending:31209
    onclick https://musescore.com/pimplup/an-ending:31082
an-ending:31218:31
    process https://musescore.com/pimplup/an-ending:31218
    rejected https://musescore.com/pimplup/an-ending:8
    (Async: promise callback)
    step https://musescore.com/pimplup/an-ending:9
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    process https://musescore.com/pimplup/an-ending:31209
    onclick https://musescore.com/pimplup/an-ending:31082
```
Download PDF fails with:
```
Error: token timeout
    timer https://musescore.com/pimplup/an-ending:26753
    setTimeout handler*getApiAuth/</< https://musescore.com/pimplup/an-ending:26752
    getApiAuth https://musescore.com/pimplup/an-ending:26751
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getApiAuth https://musescore.com/pimplup/an-ending:26697
    getFileUrl https://musescore.com/pimplup/an-ending:26779
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getFileUrl https://musescore.com/pimplup/an-ending:26776
    rs https://musescore.com/pimplup/an-ending:26817
    exportPDF https://musescore.com/pimplup/an-ending:26810
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    exportPDF https://musescore.com/pimplup/an-ending:26807
    downloadPDF https://musescore.com/pimplup/an-ending:26835
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    downloadPDF https://musescore.com/pimplup/an-ending:26830
    action https://musescore.com/pimplup/an-ending:31358
    process https://musescore.com/pimplup/an-ending:31214
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    process https://musescore.com/pimplup/an-ending:31209
    onclick https://musescore.com/pimplup/an-ending:31082
an-ending:31218:31
```
And Download MP3 fails wth:
```
Error: token timeout
    timer https://musescore.com/pimplup/an-ending:26753
    setTimeout handler*getApiAuth/</< https://musescore.com/pimplup/an-ending:26752
    getApiAuth https://musescore.com/pimplup/an-ending:26751
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getApiAuth https://musescore.com/pimplup/an-ending:26697
    getFileUrl https://musescore.com/pimplup/an-ending:26779
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    getFileUrl https://musescore.com/pimplup/an-ending:26776
    action https://musescore.com/pimplup/an-ending:31369
    normalizeUrlInput https://musescore.com/pimplup/an-ending:31193
    download https://musescore.com/pimplup/an-ending:31199
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    download https://musescore.com/pimplup/an-ending:31198
    process https://musescore.com/pimplup/an-ending:31214
    __awaiter https://musescore.com/pimplup/an-ending:10
    __awaiter https://musescore.com/pimplup/an-ending:6
    process https://musescore.com/pimplup/an-ending:31209
    onclick https://musescore.com/pimplup/an-ending:31082
an-ending:31218:31
```

**Comment by AngelaVilladiego** [comment] 2024-03-10 01:23
Downloads fail on the command line tool, Firefox desktop Tampermonkey script, as well as the bookmarked javascript code in both Firefox and Chrome mobile browsers.

The command line error code is as follows:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "function Error() { [native code] }".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by AngelaVilladiego** [comment] 2024-03-11 01:56
It seems to be working now. At least on my end, I realized that Musescore itself was having an issue where only the first image of the sheet music was loading. It appears their servers were having issues. Now that the website is running properly, the extension works as expected!

**Comment by PeterNjeim** [comment] 2024-03-14 16:09
Duplicate of #44 and #51

**Closed by PeterNjeim** 2024-03-14 16:09 UTC
Labels: bug, duplicate, musescore issue
