### ISSUE TITLE
Command-line PDF download results in corrupted file

### ISSUE THREAD

**Issue by fractured345** [LibreScore/dl-librescore#31] opened 2023-08-15 18:17 UTC
pdf when downloaded and converted from command broken and not usable

**Comment by PeterNjeim** [comment] 2023-08-16 17:07
Information unclear, you must provide enough information to diagnose the problem, such as the song you're trying to download, the specific details of what's broken and usable (not "useable"), etc.

**Comment by dev-frid** [comment] 2023-08-17 09:12
@PeterNjeim Running into the same issue.

Example: /user/3270391/scores/10146049

My OS throws this error:
<img width="317" alt="image" src="https://github.com/LibreScore/dl-librescore/assets/129059057/b755b9ab-321f-44c9-bed9-79d74cf6b123">

I am unable to open the file anywhere, including in a browser.

**Comment by ultravioletcatastrophe** [comment] 2023-08-18 18:43
Same issue. Tried multiple PDF readers

**Comment by arashi-dev** [comment] 2023-08-31 17:56
I am experiencing the same issue while using the CLI (on windows 10)
I can help if you need

**Comment by fractured345** [comment] 2023-08-31 18:19
i would like that

**Comment by fractured345** [comment] 2023-08-31 18:36
![Screenshot (1018)](https://github.com/LibreScore/dl-librescore/assets/89229998/d5efa110-aed2-42eb-a775-51b7fe5f237f)

**Comment by fractured345** [comment] 2023-08-31 18:36
dosent load

**Comment by SquarishRectangle** [comment] 2023-09-02 03:32
Same issue on Win10 and Ubuntu 22.04LTS through WSL. 
Rolled back multiple versions and the error persists. Makes me think this may be caused by musescore changing something on their end.

**Comment by catzhead** [comment] 2023-09-02 17:49
Hello,
Just in case it could be useful, two other links that don't work in a similar way:
https://musescore.com/user/20827041/scores/8676426
https://musescore.com/user/85337/scores/6144002

I'm using MacOS 13.4.1 on an Intel macbook pro 2019, npm 9.6.3 installed via brew

Thanks for the tool, hope you can find the problem!

**Comment by CarlyRaeJepsenStan** [comment] 2023-09-09 00:07
Can confirm, same issue when using `npx dl-librescore@latest` results in a corrupted PDF file. Using latest versions of Node.js and npx/npm

**Comment by Spixmaster** [comment] 2023-09-11 05:57
Yes, .mid and .mp3 work but the PDF is broken. I think it is the case for every song so no example is needed.

**Comment by TheMelonGod** [comment] 2023-09-12 21:28
I'm having the same problem, but the dickhead that owns this program deleted all the comments. Did anybody figure it out before the control freak turned this comment section into Nazi Germany? Thanks in advance.

**Comment by PeterNjeim** [comment] 2023-09-13 01:07
> I'm having the same problem, but the dickhead that owns this program deleted all the comments. Did anybody figure it out before the control freak turned this comment section into Nazi Germany? Thanks in advance.

Reactions were added to GitHub for the sole reason of preventing "+1" comments. Click the thumbs up button and move on

**Comment by Mindos2055** [comment] 2023-09-22 03:16
Also getting this issue. On Arch Linux using command line tool.

**Comment by ZhymabekRoman** [comment] 2023-09-23 15:15
I write tool to download PDF from Musescore. Perhaps it can be useful for someone: https://github.com/ZhymabekRoman/musescore_pdf_downloader

**Comment by arashi-dev** [comment] 2023-09-29 18:03
I just attached the `main.user.js` file in the PR which can be used with `tampermoneky` until this PR gets merged. you can also use the commit to build your own `main.user.js` file or cli if you don't trust the attached file :)

**Closed** 2023-09-29 18:34 UTC
Labels: bug
