### ISSUE TITLE
Application doesn't launch on Ubuntu 24

### ISSUE THREAD

**Issue by MM4096** [LibreScore/dl-librescore#73] opened 2024-07-15 04:16 UTC
I'm running Ubuntu 24, and when running the AppImage, I get the following output:
```
/bin/sh: /tmp/.mount_LibreSR3Pfkz/lib/libc.so.6: version `GLIBC_2.38' not found (required by /bin/sh)
/bin/sh: /tmp/.mount_LibreSR3Pfkz/lib/libc.so.6: version `GLIBC_2.38' not found (required by /bin/sh)
/bin/sh: /tmp/.mount_LibreSR3Pfkz/lib/libc.so.6: version `GLIBC_2.38' not found (required by /bin/sh)
/bin/sh: /tmp/.mount_LibreSR3Pfkz/lib/libc.so.6: version `GLIBC_2.38' not found (required by /bin/sh)
/tmp/.mount_LibreSR3Pfkz/AppRun: line 4: 514402 Segmentation fault      (core dumped) LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib" LD_PRELOAD="$(ldconfig -p | grep "libstdc++\..*x86-64" | awk -F '=> ' 'NF>1{ sub(/ .*/,"",$NF); print $NF }' | head -n 1):$(ldconfig -p | grep "libm\..*x86-64" | awk -F '=> ' 'NF>1{ sub(/ .*/,"",$NF); print $NF }' | head -n 1):$(ldconfig -p | grep "libc\..*x86-64" | awk -F '=> ' 'NF>1{ sub(/ .*/,"",$NF); print $NF }' | head -n 1):$(ldconfig -p | grep "librt\..*x86-64" | awk -F '=> ' 'NF>1{ sub(/ .*/,"",$NF); print $NF }' | head -n 1)" "${APPDIR}/librescore" "$@"
```
However, running `ldd --version` returns `ldd (Ubuntu GLIBC 2.39-0ubuntu8.2) 2.39`.

Basically, the application doesn't run, citing missing libraries that do exist.

**Comment by PeterNjeim** [comment] 2024-07-16 22:34
Wrong repository, duplicate of https://github.com/LibreScore/app-librescore/issues/56

**Closed by PeterNjeim** 2024-07-16 22:34 UTC
