### ISSUE TITLE
CLI can't download PDF of official score

### ISSUE THREAD

**Issue by weiluntong** [LibreScore/dl-librescore#83] opened 2024-10-04 23:41 UTC
It looks like we're trying to index an array, and it fails to do that? Not entirely sure on the inner workings though.

### Environment:
Node.js version: Node.js v20.18.0

Note: Run through a docker container using `docker run --rm -it --entrypoint /bin/bash node:lts-slim`

### steps to reproduce:
1. `npx dl-librescore@latest`
2. Paste this and press enter: `https://musescore.com/user/39593079/scores/19113982`
3. type `a` at the file selection and press enter
4. Press enter to save to default output directory `/` (was just testing the app so I just let it save here by just pressing enter)

### Stacktrace:
```
⠁ Processing…/root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:5015
        const imgtype = thumbnail.match(/score_0\.(\w+)/)[1];
                                                         ^

TypeError: Cannot read properties of null (reading '1')
    at get imgType [as imgType] (/root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:5015:58)
    at /root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:31854:27
    at Generator.next (<anonymous>)
    at /root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:16:12)
    at exportPDF (/root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:31853:56)
    at /root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:32381:50
    at Generator.next (<anonymous>)
    at /root/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:20:71
```

**Comment by PeterNjeim** [comment] 2024-10-11 18:18
Duplicate of https://github.com/LibreScore/dl-librescore/issues/10

**Closed** 2024-10-11 18:17 UTC
Labels: duplicate, invalid

**Comment by weiluntong** [comment] 2024-10-11 22:38
Hmmm... While I can appreciate the reply, the motive, and the resolution of the issue (setting it as will not fix), I'd like to point at another aspect of the problem hinted at with my title.

I'm OK if we don't want to allow downloading official scores with this app. I'll accept that, but we shouldn't let it crash right? We should handle it more gracefully?

**Comment by PeterNjeim** [comment] 2024-10-12 07:09
I set it as "not planned", which includes 4 categories, one of which is "duplicate". We don't choose not to support official scores, we simply can't support them. MIDI and MP3 work for some official scores but not others. An error message indeed could be shown, will work on that later
