### ISSUE TITLE
cli uncaught error mac

### ISSUE THREAD

**Issue by JustinGuese** [LibreScore/dl-librescore#60] opened 2024-03-12 18:12 UTC
⠁ Processing…node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "function Error() { [native code] }".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v21.7.1

**Comment by PeterNjeim** [comment] 2024-03-14 16:26
Duplicate of #44

**Closed by PeterNjeim** 2024-03-14 16:26 UTC
Labels: bug, duplicate
