### ISSUE TITLE
Download buttons not appearing

### ISSUE THREAD

**Issue by coo123123** [LibreScore/dl-librescore#89] opened 2024-11-22 00:26 UTC
it doesnt work maybe its because musescore updated

![image](https://github.com/user-attachments/assets/25fface9-7337-4e9f-b321-1fd594df93ac)

**Comment by PeterNjeim** [comment] 2024-11-22 08:09
Can't reproduce. Please open the Tampermonkey menu by clicking on the Tampermonkey icon in the extensions area of your browser. If there's a message in blue at the top asking you to enable developer mode, you must do that then refresh the page.

If that isn't your issue, please take a screenshot of the Tampermonkey menu and send it here

**Comment by AdityaMH** [comment] 2024-11-25 09:57
Browser who support userscript like soul browser also didn't work too.

**Comment by PeterNjeim** [comment] 2024-11-25 16:27
For people having issues, please follow the instructions I sent earlier or else I can't help you

**Comment by AdityaMH** [comment] 2024-11-26 02:06
> it doesnt work maybe its because musescore updated
> 
> ![image](https://private-user-images.githubusercontent.com/189302643/388744199-25fface9-7337-4e9f-b321-1fd594df93ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODY0NTksIm5iZiI6MTczMjU4NjE1OSwicGF0aCI6Ii8xODkzMDI2NDMvMzg4NzQ0MTk5LTI1ZmZhY2U5LTczMzctNGU5Zi1iMzIxLTFmZDU5NGRmOTNhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTU1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM0YmQ2ODNmZGRlODZiNDczNTkxYzgyZWE1NTE3NzVhODBlNWZiZWRkNmI3Njc0MzRiYjkwZWM3MWRmYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nGa0od891TznXY-Ly8YWXJdPOJ3s9iX-RzO9kEpElLA)

Are you on mobile browser?

**Comment by PeterNjeim** [comment] 2024-11-26 02:33
The screenshot shows the desktop layout, as well as scrollbars, indicating it's desktop

**Comment by AdityaMH** [comment] 2024-11-26 06:06
> The screenshot shows the desktop layout, as well as scrollbars, indicating it's desktop

![Screenshot_20241126-130130](https://github.com/user-attachments/assets/8522e1b5-6f89-4037-91c4-7cde3ba0a308)
 

Also didn't work using kiwi browser with tampermonkey too.

**Comment by PeterNjeim** [comment] 2024-11-26 06:12
As I said earlier, I can't help anyone until they follow my instructions in the first message I sent. Also, I'm not sure why you're quoting me, it isn't related to your comment

**Comment by AdityaMH** [comment] 2024-11-26 08:03
Follow your intructions and enable developer mode still didn't work.

**Comment by PeterNjeim** [comment] 2024-11-26 17:23
In my instructions, I said if this wasn't your issue to send a screenshot of the Tampermonkey menu here. Also something else to try: scroll down a few pages on the left, the buttons might appear afterwards. Also, try scrolling down to the bottom on the right, the buttons might be stuck on the bottom

**Comment by Zerdeja-13** [comment] 2024-11-28 20:05
> In my instructions, I said if this wasn't your issue to send a screenshot of the Tampermonkey menu here. Also something else to try: scroll down a few pages on the left, the buttons might appear afterwards. Also, try scrolling down to the bottom on the right, the buttons might be stuck on the bottom

thank you! this was actually the "issue". just scroll bottom of the left side (partiture) and the download buttons apeared
![Captura de pantalla (80)](https://github.com/user-attachments/assets/75a192d4-44df-4ca6-b1d4-39b70caf546d)

**Comment by PeterNjeim** [comment] 2024-11-28 20:16
Glad you got it working. I'm planning on changing how the buttons work in the future so this won't happen again

**Comment by AdityaMH** [comment] 2024-11-29 04:50
Oh boy, it's working again because using wrong tampermonkey for kiwi browser.

But for soul browser still didn't work because support userscript but not extension.

**Comment by PeterNjeim** [comment] 2024-12-06 08:54
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)

**Closed by PeterNjeim** 2024-12-06 08:54 UTC
Labels: bug, help wanted

**Comment by AdityaMH** [comment] 2024-12-06 21:10
Better button place.

Still not work for Soul browser yet.

**Comment by PeterNjeim** [comment] 2024-12-06 21:25
I closed this issue due to fixing the issue creator's problem. While you explained your issue here, it wasn't the right place for it. Please create a new issue to track yours specifically

**Comment by SANTIZAS** [comment] 2024-12-10 18:15
Hola necesito ayuda. Lo que pasa es que ya instale el escript pero no me deja descargar y ahorita me aparecia que estaba en ejecución y ya no. Me pueden colaborar

![image](https://github.com/user-attachments/assets/c1722f44-ebed-43c7-ab54-8ed026ef5144)
![image](https://github.com/user-attachments/assets/40357399-0aa0-466c-9731-b59c7c354f59)

**Comment by SANTIZAS** [comment] 2024-12-10 18:17
Ya me aparecio y ahora que procedo a hacer? 

![image](https://github.com/user-attachments/assets/193b68c2-de71-4520-b95d-84361e26c8b5)

**Comment by PeterNjeim** [comment] 2024-12-10 19:04
@SANTIZAS Por alguna razón, tu script de usuario no se activa. Debería aparecer un cuadrado rojo con un "1" en él, lo que indica que el script se ha activado. No estoy seguro de qué podría estar causando el problema. ¿Puedes intentar usarlo en una ventana privada del navegador? ¿Puedes intentar desinstalar Tampermonkey y seguir las instrucciones nuevamente? Tal vez puedas probar con otro navegador y ver si funciona. Cuéntame tus resultados
![image](https://github.com/user-attachments/assets/22bce1ae-7f79-4d50-a5d6-ed768449edb2)

**Comment by SANTIZAS** [comment] 2024-12-10 20:07
Me puedes colaborar mandandome el archivo es que son tantos que perdi el link donde lo descargue, es que era este y ese otro y solo encontre ese.

![image](https://github.com/user-attachments/assets/8716fde5-88dd-453a-8d6e-d9c38b780fb7)

**Comment by PeterNjeim** [comment] 2024-12-10 21:18
@SANTIZAS 

Tienes instalado el archivo correcto (que está [aquí](https://github.com/LibreScore/dl-librescore/blob/master/docs/es/LÉAME.md#extensión-del-navegador)). El problema es que el script de usuario no se activa por alguna razón.

Prueba a habilitar Tampermonkey para su uso en una ventana privada del navegador (haz clic derecho en el icono de Tampermonkey, haz clic en "Administrar extensión" y marca la casilla "Permitir en modo incógnito") (además, asegúrate de que "Acceso al sitio" esté configurado en "En todos los sitios"):
![image](https://github.com/user-attachments/assets/71af98fb-e178-44b2-8328-63e673e0c898)
<img src="https://github.com/user-attachments/assets/f6e19147-9828-42bc-9a9d-12ad69cd69b4" height="256" alt="image">
Una vez que hayas hecho esto, abre una ventana privada del navegador (Ctrl+Shift+N) y ve a una canción en musescore.com y comprueba si funciona. Si funciona, significa que hay una determinada extensión que usas en Chrome que está en conflicto con Tampermonkey.

Si no funciona, intenta abrir un navegador diferente (como Microsoft Edge) y sigue las instrucciones de GitHub vinculadas anteriormente para ver si funciona allí. Si funciona, significa que hay una determinada extensión en Chrome que está en conflicto con el script de usuario.

Si eso tampoco funciona, entonces realmente no sé cuál podría ser el problema

**Comment by SANTIZAS** [comment] 2024-12-11 19:28
Hola!!! Efectivamente ya se como solucionar eso:
Tienen que darle aceptar a ser desarrollador en la parte superior de la derecha, luego acceso a los sitios, a todos los sitios. 
![image](https://github.com/user-attachments/assets/0e7bc044-f516-432c-8abb-79e53309b389)
![image](https://github.com/user-attachments/assets/39f5a422-4ef2-4263-ab6c-f3c3f303b861)
![image](https://github.com/user-attachments/assets/b97d7a4a-6341-4a05-8267-bbe51be896f2)

La verdad crei que no funcionaba y ya puedoooo se los recomiendo de verdad.

**Comment by SANTIZAS** [comment] 2024-12-11 19:35
Ya quede feliz!

Lo unico que me queda pensando es como se actualiza, por donde se hace, que pasos toca seguir para actualizar si la pagina cambia! Podrias decir el paso a paso como ahorita? Como ver el archivo para descargar el script e intslarlo 

![image](https://github.com/user-attachments/assets/3da8ab29-76be-4bb3-9276-fc2de1ef782d)
![image](https://github.com/user-attachments/assets/b2655094-d1fb-4b95-8b09-f15e3a6c8833)
![image](https://github.com/user-attachments/assets/6d81b7a2-69dd-4a76-aaa3-d95aed0ad83e)

**Comment by PeterNjeim** [comment] 2024-12-11 19:38
Tampermonkey debería actualizar automáticamente el script. Para asegurarse de que la actualización automática esté activada, vaya al Dashboard de Tampermonkey, haga clic en la pestaña "Configuración" y, luego, en la parte inferior, asegúrese de que el "Intervalo de verificación" no esté configurado en "Nunca" (yo lo configuré en 6 horas) y que el "Intervalo de actualización" esté configurado en "Siempre".
