### ISSUE TITLE
CLI can't download PDF's of Official Scores

### ISSUE THREAD

**Issue by m41w4r3exe** [LibreScore/dl-librescore#37] opened 2023-11-28 23:21 UTC
Thank you for the amazing library!

Some scores, which are removed from the website, can still be downloaded via Tampermonkey Userscript, however they don't work with CLI.

like this: https://musescore.com/official_author/scores/6920219

any idea why?

**Comment by PeterNjeim** [comment] 2023-11-30 23:21
Duplicate of #10

**Closed by PeterNjeim** 2023-11-30 23:21 UTC
Labels: duplicate, invalid
