### ISSUE TITLE
CLI can't download PDF's of Official Scores

### ISSUE THREAD

**Issue by mycielski** [LibreScore/dl-librescore#41] opened 2023-12-22 16:11 UTC
<img width="838" alt="image" src="https://github.com/LibreScore/dl-librescore/assets/76878490/b4462dfd-9719-4989-ab1f-f6ee153fb399">

**Comment by pe5er** [comment] 2023-12-28 12:00
exact same error for me, different score, only happens when selecting PDF

**Comment by PeterNjeim** [comment] 2024-01-03 00:08
Duplicate of #10

**Closed by PeterNjeim** 2024-01-03 00:08 UTC
Labels: duplicate, invalid
